version: '2'

services:
  app:
    build:
      context: ../OnlineBanking
    container_name: app
    depends_on:
      - db
      - pgadmin
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgdb:5432/hdfcbank1
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
  db:
    container_name: pgdb
    image: 'postgres:13.1-alpine'
    ports:
      - 6543:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    container_name: pgadmin
    image: 'dpage/pgadmin4'
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
volumes:
  database_data:
    driver: local